title: Jonathan Mastin # your name (or website title) here
logo: "https://i.postimg.cc/QM2PWPP6/JMas.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data driven analyst who loves solving problems! <br><br> 
  Passionate about Fitness and Investing  <br><br>
  <a href="https://www.linkedin.com/in/jonathanmastin1913/">View My LinkedIn Profile</a> 
  
theme: Jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
